Feature/ccn 199 dashboard styling rework
TKSpectro/corona-check-in pull request #107
Opened 2023-03-20 17:42 UTC by TKSpectro

2023-03-20 18:26 UTC, TKSpectro commented
@ddepta ist alles gepusht. Kann reviewed werden

2023-03-21 23:02 UTC, ddepta requested changes
siehe Kommentare, inline-style auslagern

2023-03-21 23:02 UTC, ddepta commented on apps/frontend/src/app/dashboard/dashboard.component.html
> +    <ccn-current-status style="width: 100%"></ccn-current-status>
bitte noch inline-style auslagern

2023-03-21 23:02 UTC, ddepta commented on apps/frontend/src/app/dashboard/dashboard.component.html
> +      style="width: 100%"
bitte noch inline-style auslagern

2023-03-21 23:02 UTC, ddepta commented on apps/frontend/src/app/dashboard/dashboard.component.html
> +    style="width: 100%"
bitte noch inline-style auslagern

2023-03-23 13:43 UTC, ddepta approved these changes

2023-03-23 13:44 UTC, merged